apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/michaelwallett/multi-stage-test:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/michaelwallett/multi-stage-test:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: multi-stage-test
        chartPath: charts/multi-stage-test
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/michaelwallett/multi-stage-test"
          image.tag: "{{.DIGEST_HEX}}"
